### ISSUE TITLE
sigsev

### ISSUE THREAD

**Issue by jadekler** [googleapis/gapic-generator-go#248]
Any idea what's up with this?

```
deklerk at deklerk-macbookpro2 in /var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/tmp.7kFeS7Av
$ protoc -I `pwd`/googleapis -I `pwd`/protobuf --go_gapic_out foo --go_gapic_out 'cloud.google.com/go/texttospeech/apiv1;texttospeech' `pwd`/googleapis/google/cloud/texttospeech/v1/cloud_tts.proto
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14e618d]

goroutine 1 [running]:
github.com/googleapis/gapic-generator-go/internal/gensample.PluginEntry(0xc0000c2060, 0xc000266d20, 0x49, 0xc000248e40)
	/Users/deklerk/go/src/github.com/googleapis/gapic-generator-go/internal/gensample/plugin.go:44 +0x5d
main.main()
	/Users/deklerk/go/src/github.com/googleapis/gapic-generator-go/cmd/protoc-gen-go_gapic/main.go:43 +0x1bc
--go_gapic_out: protoc-gen-go_gapic: Plugin failed with status code 2.
```

**Comment by noahdietz** [comment]
@hzyi-google looks like there is an issue in the samplegen code. Mind taking a look? Thanks!

**Comment by hzyi-google** [comment]
Yes I'll look into it.

**Comment by hzyi-google** [comment]
Hey Jean, the second `--go_gapic_out` should have been `--go_gapic_opt` instead - the go package is a protoc plugin option.

Also, I _think_ you need to specify the go package like this (see [docker_entrypoint](https://github.com/googleapis/gapic-generator-go/blob/6fcabf481222feb86fe6402c464fd5ca658e4e90/docker-entrypoint.sh#L57))

```
--go_gapic_opt 'go-gapic-package=cloud.google.com/go/texttospeech/apiv1;texttospeech'
```
