### ISSUE TITLE
Regression: Index out of range

### ISSUE THREAD

**Issue by valery-barysok** [googleapis/gapic-generator-go#747]
#### Environment details

  - Programming language: golang
  - OS: mac os
  - Language runtime version: 1.17
  - Package version: github.com/googleapis/gapic-generator-go v0.23.0

#### Steps to reproduce

  Define a service without methods like:
  
  ```proto
  service MyService {
       option (google.api.default_host) = "my.service.com";
  }
  ```
 
The issue is located at https://github.com/googleapis/gapic-generator-go/blob/master/internal/gengapic/doc_file.go#L90
 
 ```
 panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/googleapis/gapic-generator-go/internal/gengapic.(*generator).genDocFile(0xc000216d80, 0x1, {0x0, 0x0, 0xb}, 0xc0003745a0)
	/go/pkg/mod/github.com/googleapis/gapic-generator-go@v0.23.0/internal/gengapic/doc_file.go:90 +0x1bfd
github.com/googleapis/gapic-generator-go/internal/gengapic.Gen(0xc000265dc0)
	/go/pkg/mod/github.com/googleapis/gapic-generator-go@v0.23.0/internal/gengapic/gengapic.go:110 +0x916
main.main()
	/go/pkg/mod/github.com/googleapis/gapic-generator-go@v0.23.0/cmd/protoc-gen-go_gapic/main.go:37 +0xf7
--go_gapic_out: protoc-gen-go_gapic: Plugin failed with status code 2.
 ```

**Comment by noahdietz** [comment]
@valery-barysok thanks for reporting this, please feel free to send a PR to fix this. Otherwise @alicejli can you take a look when you get a chance?
